### ISSUE TITLE
Sketch selection

### ISSUE THREAD

**Issue by ojthetiny** [cryinkfly/Fusion-360---Linux-Wine-Version-#89] opened 2021-09-12 00:55 UTC
Has some major issues with certain parts of a sketch not being selectable without selecting the entire sketch which defeats the entire sketch useless and the program unusable. I don't know what this is about as it's happening on both dxvk and opencl drivers.

**Comment by blazej222** [comment] 2021-09-13 05:27
Possible duplicate of #66 and #73. What drivers and OS are you using? Can you provide photos/videos of what exactly happens? Does the program select the objects, but won't highlight them (you can check by selecting and doing move operation for example), or is it completely impossible to select some objects?

**Comment by cryinkfly** [comment] 2021-09-13 14:25
@ojthetiny Please check the other issues https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/issues/66 and https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/issues/73 + answer there of this question:

> What drivers and OS are you using? Can you provide photos/videos of what exactly happens? Does the program select the objects, but won't highlight them (you can check by selecting and doing move operation for example), or is it completely impossible to select some objects?

**Closed by cryinkfly** 2021-09-13 14:25 UTC
Labels: bug
