### ISSUE TITLE
Crashes on splash screen

### ISSUE THREAD

**Issue by vintagepc** [cryinkfly/Fusion-360---Linux-Wine-Version-#38] opened 2021-07-04 00:59 UTC
OpenSuSE 15.3 on a new computer with a fresh install of WINE 6.12 from the Emulators repo. 

Install completes without issue but on launch it sits on the initial splash screen for a few minutes and then crashes. 

![image](https://user-images.githubusercontent.com/53943260/124370075-13e9b380-dc41-11eb-861e-fece4e938bc2.png)

Also tried `rsync` ing the drive_c and .reg files from a working wineprefix on another machine. This one gets to the login screen, but then refuses to actually accept/draw any typed characters.
This other code has a different ProgramData folder install so I am wondering if Autodesk published an update that no longer works. I'll see if I can locate the same installer used on the other machine and install from that instead.

**Comment by theol0403** [comment] 2021-07-04 03:43
Duplicate of #29

**Comment by vintagepc** [comment] 2021-07-04 11:51
I'm not convinced it's the same issue. I was never even able to sign in on this install, and it takes a good 2-3 minutes to crash from when the splash screen is shown. 

the "working" install I copied goes from splash to authentication page in about 15 seconds.

**Comment by cryinkfly** [comment] 2021-07-04 15:08
@vintagepc Which graphics card and desktop environment did you have installed?

**Comment by vintagepc** [comment] 2021-07-04 15:11
KDE, this is with an nVidia GTX-1050 and proprietary drivers. 

I've tried both the dxvk and opengl installation options and it makes no difference in the issue.

**Comment by cryinkfly** [comment] 2021-07-04 15:26
Okay, then I use XFCE on my system.

**Comment by theol0403** [comment] 2021-07-04 16:03
> I'm not convinced it's the same issue. I was never even able to sign in on this install, and it takes a good 2-3 minutes to crash from when the splash screen is shown. 

My bad, the other issue indeed takes you to the login before crashing.

**Comment by alice-cash** [comment] 2021-07-05 05:09
I am having the same issue. Launch, splash screen for 2 minutes then crash report. Just tried to install it today.
Running Xubuntu 20.04 and Geforce 1080 with proprietary drivers

**Comment by cryinkfly** [comment] 2021-07-05 11:55
@alice-cash Okay, can you check if my script have created the file NMachineSpecificOptions.xml correctly?

… and also if winetricks have installed corefonts vcrun2019 … ? 😊

**Comment by vintagepc** [comment] 2021-07-05 12:30
> Okay, then I use XFCE on my system. Maybe it this the reason why it doesn’t work for you.
> 
> Have you also other repository’s configured?

Just Emulators/Wine and packman. 

If this was a system or package issue I'd expect the copied wineprefix version to fail the same way, yet it acts normal. Unfortunately I just can't get further than sign-in on that one because it won't accept keyboard input. This really smells like something they updated on their end. 

This is one of the main reasons I despise SaaS and quasi-cloud stuff; it can break without any changes on your part and good luck figuring out why.

I haven't had time yet to dig up the installer from the previous machine I was using; I just went back to my VM and a different CAD program so the motivation to spend more time getting it working again has waned a bit. :roll_eyes: 

Suggestion - maybe the scripts could maintain checksums of the known working installers so that one can more easily check to see if it's a "known" revision or if they've sneakily updated it and potentially broken something - and if it detects a new installer ask the user to report their success or failure here for others.

**Comment by Nold360** [comment] 2021-07-05 15:57
I'm struggeling with the same issue. I fixed it somehow a few days ago.. but forgot how and where... so I'm back here, trying to figure out what's wrong.. pretty sure it was some missing winetricks lib or something like that...

**Comment by alice-cash** [comment] 2021-07-05 16:27
So I am not as familiar with wine and verifying packages are installed, I tried just reinstalling both and get `vcrun2019 already installed, skipping` and `corefonts already installed, skipping`. I also verified that NMachineSpecificOptions.xml is set up. 

I also tried setting up with dxvk but get the exact same issue.

I have also tried reinstalling graphics drivers and updating from 460 to 465. I am clearing out $HOME/.fusion360 between attempts, if I should be doing something else let me know. Other programs like steam proton/games work.

**Comment by cryinkfly** [comment] 2021-07-05 17:16
The whole thing is really strange. 😪

**Comment by cryinkfly** [comment] 2021-07-05 18:50
Hello everyone,

I have closed some issues now and referred to this issue here, which are basically similar to this one. ⚠️

So I hope that we can find faster a solution for this problem. 🧔🏼‍♂️👩🏽‍🦱👱🏾‍♀️👨🏻‍🦱🧑🏼‍🦱👩🏻👨🏿‍🦲🌎

**Comment by vintagepc** [comment] 2021-07-05 19:36
Additional data point: Moving the "crashing" install to the "working" prefix results in it starting and moving to the still-unusable sign-in page. 

So we are back to it being a prefix config issue as part of the problem.

**Comment by cryinkfly** [comment] 2021-07-05 20:51
@vintagepc I just find it frightening that it works with one of them and with the other, who even has the same hardware, etc., it doesn't work.

I don’t know, why it’s so.

**Comment by suryanisaac** [comment] 2021-07-06 03:27
Good to know that it's not a Manjaro-only problem, so that can probably eliminate KDE and Manjaro playing a part in the error.

Does installation work properly for you all too? The install script successfully works for me.

**Comment by hopkuba** [comment] 2021-07-06 05:51
@suryanisaac Installer after some additional lib installs is fine but these wine-3d errors when I started from the console. It even popped up some dll name before crash... I think it might be a missing lib of some kind that is not letting some 3d rendering data to pass through. From some basic analisis of GPU Usage and programs that are using it I think that Fusion is loading default 3d view even before login for optimized loading. Thats why there are wine-3d errors I think. I don't know wine that well but maybe some 3d packets are not installed or something.

**Comment by hopkuba** [comment] 2021-07-06 05:54
`wine: Call from 0x7b02dae6 to unimplemented function ucrtbase.dll.feclearexcept, aborting`

> It even popped up some dll name before crash...

This message showed up right before crash in console.

**Comment by hopkuba** [comment] 2021-07-06 07:28
I have something that might help. My workshop PC running Win7 was dealing with Fusion just fine about a week ago. Today I tried to start it and all 3d is gone. No 3d interface at all. I think that it may be a sneaky update changing some way that autodesk handles  3D

**Comment by suryanisaac** [comment] 2021-07-06 07:34
Hmm, It's worked for me on the same system configuration a few weeks ago but not now. Does anyone here know of an archive of Fusion360 .exe files? 

So it's probably Autodesk that broke something?

 Anyway through this whole ordeal, I'm learning more and more FreeCAD which is good I guess.

**Comment by hopkuba** [comment] 2021-07-06 08:31
FreeCad has some CNC module? That's a deal breaker for me. If it has - I am switching right now.

**Comment by suryanisaac** [comment] 2021-07-06 10:37
Yes! https://wiki.freecadweb.org/Path_Workbench

**Comment by suryanisaac** [comment] 2021-07-06 10:39
Also something interesting @cryinkfly and @vintagepc I've found this script to work: https://gist.github.com/probonopd/0fab254aa0b6fc371d8db641822bd530#gistcomment-2799597

I followed the instructions and Fusion360 launched without a problem, on the same machine without any changes. Maybe it's something with the winetricks installed? I've also tried this after attempting your install on my system so that might play a part.

**Comment by cryinkfly** [comment] 2021-07-06 10:43
So I have found out, that it sometimes happens that not all packages are available, as you can see in the picture for example:

![Bildschirmfoto_2021-07-06_12-26-26](https://user-images.githubusercontent.com/79079633/124585640-c85c2300-de55-11eb-8c4c-a58e71b871c8.png)

... and this package is needed for the TLS and HTTPS story, for example!

Here you can see it on my system:

![Bildschirmfoto_2021-07-06_12-40-46](https://user-images.githubusercontent.com/79079633/124587006-70262080-de57-11eb-9ea2-8d4fe9785081.png)

---

Then I have searched and found this site here: https://github.com/lutris/docs/blob/master/WineDependencies.md

... where I get a information that we need sometimes more packages and so I think that some users must install these things here for using Autodesk Fusion 360 correctly on there system!

Also I think when I install more of these packages then maybe it could be that other things will also work for us.
As an example, there is the documentation workspace.

**Comment by cryinkfly** [comment] 2021-07-06 10:54
@suryanisaac 

## Winetricks definitely plays a very big role in this whole thing!

The problem is that sometimes the servers are not reachable or the sha256sum are mismatched and that takes care of it ensures that not everything is installed correctly!!!

And this can be also the reason why some users can't use the program Autodesk Fusion 360 on there system.

But at the moment I can't do anything, because it always depends on the availability of this server!

**Comment by vintagepc** [comment] 2021-07-06 11:17
It also doesn't help if a distro has system packages for certain things that might interfere or conflict with things that winetricks might add. 

In any case I've also had enough of this Autodesk BS and have been using SolidEdge Community more and more as I get to know it. (Only reason I still hang on to F360 is for things I haven't figured out how to do yet. I guess this will be more motivation than any as the time spent messing around with F360 in wine is outweighing the time it takes to start up and shutdown a VM now - Fusion has lost the "convenience" factor.

No "cloud", once it's installed, it's installed, end of story. Also doesn't phone home to the mother-ship. 
Graphics don't seem as intensive as Fusion so it runs fine in a Win7 VM in Virtualbox
Free for hobbyists/makers/tinkerers

https://www.plm.automation.siemens.com/plmapp/education/solid-edge/en_us/free-software/community

the 2020 version will happily install with the correct prerequisites (Dot Net and some IE related requirements) but unfortunately crashes when trying to create a new document or open one. (But even that's a huge step forward, in Wine 5.x it would not even get past the splash screen. 
It installs and launches in Wine but there is a showstopper where it crashes if you try to open or create a document. Alas I'm not well versed enough in wine debugging to understand what it needs.

I've tried FreeCAD a few times but always found the interface a horrible mess and it's a challenge to find out how to do anything when all the search results are out of date because things have been rearranged and not where it says they should be. I genuinely hope it improves and gets better but from my perspective it's been a complete non-starter any time I've tried.

**Comment by suryanisaac** [comment] 2021-07-06 12:02
Well, FreeCAD is something i'm fine with for simple parts but anything slightly complex is hard. But it's improving a lot lately and i'm hoping that it becomes better over time.

**Comment by cryinkfly** [comment] 2021-07-18 09:59
The problem was some users have with Autodesk Fusion 360 on Linux with Wine🍷, I can say that this problem is also represented on windows! 

Here is the link: https://knowledge.autodesk.com/support/fusion-360/learn-explore/caas/sfdcarticles/sfdcarticles/Fusion-360-has-installed-but-will-not-launch.html

**Comment by oschwartz10612** [comment] 2021-07-26 03:05
I have the following errors in `.fusion360/drive_c/users/owen/Local Settings/Application Data/Autodesk/Web Services/Log/WebServices.log`

```
2021-07-26T02:51:56.762Z [Fusion360:232, 596] [AdWebServices ERROR] Application not installed properly. File libcrypto-Ad-1_1-x64.dll could not be located in application dir or current dir.
2021-07-26T02:51:56.764Z [Fusion360:232, 596] [AdWebServices ERROR] Application not installed properly. File libssl-Ad-1_1-x64.dll could not be located in application dir or current dir.
```

Is this what we are looking for?

**Comment by PEERCRED** [comment] 2021-07-31 14:57
https://gist.github.com/probonopd/0fab254aa0b6fc371d8db641822bd530#gistcomment-2799597 also worked for me. Welp, actually one only need
```
winetricks atmlib gdiplus msxml3 msxml6 vcrun2017 ie8 corefonts fontsmooth=rgb winhttp win10
```
from that comment. Fusion 360 won't start with `winetricks d3d11=disabled` and you don't need to patch the installer.

**Comment by PEERCRED** [comment] 2021-07-31 16:19
Actually, didn't notice that 
```
winetricks atmlib gdiplus msxml3 msxml6 vcrun2017 ie8 corefonts fontsmooth=rgb winhttp win10
```
fails at installing `ie8` (needs 32-bit prefix). Removed `ie8` and added `dxvk` + `sh winetricks d3d10core=disabled d3d11=builtin d3d9=builtin dxgi=builtin`. (Now `wineserver` doesn't consume 100% CPU.)

**Comment by cryinkfly** [comment] 2021-08-01 20:20
@ Can you testing my new version of the installation-script, please. 🕛

**Comment by alice-cash** [comment] 2021-08-02 05:13
I can confirm the latest install script works and Fusion launches now without issue. Though the object browser items seem to be stuck in the foreground and are currently on top of my chrome window.

**Comment by cryinkfly** [comment] 2021-08-02 09:05
@alice-cash Thank you for your report. 👌

**Closed** 2021-08-02 09:06 UTC
Labels: bug, help wanted
